### PR TITLE
Preventing before_save callback from being called twice after a child create

### PR DESCRIPTION
**Pull request by kcdragon**
PR for #3631

### CODE REVIEW

**Comment by jonhyman** [comment]
@arthurnn, can this be merged? Seems like a reasonable fix from what I can tell.

**Comment by arthurnn** [comment]
Missing a changelog.
Will merge after is added.

**Comment by jonhyman** [comment]
@arthurnn https://github.com/mongoid/mongoid/pull/4066 adds a changelog for this.

**Comment by arthurnn** [comment]
thanks merged via https://github.com/mongoid/mongoid/commit/d0c460a7fe5601d52bccedf228242ff6f5665ba0

**Pull request closed without merging**
