### PR TITLE
Ruby 2.2 Ready in 3.1.0-stable

### PR DESCRIPTION
**Pull request by tonyta**
Rails [`3-2-stable`](https://github.com/rails/rails/tree/3-2-stable) was [updated to be Ruby 2.2 compatible](https://github.com/rails/rails/pull/18306), with a release pending a security issue:
> [There] will be not any new release of 3-2-stable branch. But if we have a security issue that needed to be fixed on 3.2, we will release from that branch.

This PR ensures Mongoid `3.1.0-stable` is also Ruby 2.2 compatible when that happens.

### CODE REVIEW

**Comment by tonyta** [comment]
[Tests pass](https://travis-ci.org/mongoid/mongoid/builds/54798195) in Ruby 2.2.1 using Ruby 2.2-ready ActiveModel `3-2-stable` branch.

**Comment by tonyta** [comment]
While I was in there, I fixed up `.travis.yml` to allow for further maintenance on the `3.1.0-stable`.

Hope this is okay in this PR. I can separate it out if you guys prefer. Thanks!

**Comment by arthurnn** [comment]
Can you squash the commits in one? thanks

**Comment by tonyta** [comment]
squashed in https://github.com/mongoid/mongoid/pull/4001

**Pull request closed without merging**
